POST http://localhost:7070/auth/login
Content-Type: application/json

{
  "email": "user2@mail.com",
  "password": "User2Password"
}

###
GET http://localhost:7070/auth/evaluate

###
POST http://localhost:7070/auth/sessions/temporary
Content-Type: application/json

{
  "email": "user2@mail.com"
}

###
POST http://localhost:7070/auth/signup
Content-Type: application/json

{
  "email": "noise0@iainschmitt.com",
  "password": "noisePassword"
}

###
POST http://localhost:7070/auth/login
Content-Type: application/json

{
  "email": "noise0@iainschmitt.com",
  "password": "noisePassword"
}

###
POST http://localhost:7070/exchange/orders/market
Content-Type: application/json

{
  "type": "incomingOrder",
  "email": "noise0@iainschmitt.com",
  "ticker": "testTicker",
  "size": 1,
  "tradeType": "BUY",
  "orderType": "Market"
}
