/*
 * This source file was generated by the Gradle 'init' task
 */

import kotlin.test.Test
import kotlin.test.assertTrue

class BackendTest {
    @Test fun placeholder() {
        assertTrue { true }
    }
}
